name: Continuous Integration on release branches

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm build
      - name: Release new package version
        run: npm semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
